import "./globals.css"

import React from 'react';
// import ThemeProvider from '@/providers/theme-provider';

import {Navbar,Footer} from '@/components';


export const metadata = {
  title: 'myMetaArt',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
          
          {/* <ThemeProvider> */}
          <Navbar/>
          <div className="pt-65">

          {children}
          </div>
          <Footer/>

          {/* </ThemeProvider> */}
      </body>
    </html>
  );
};